Update for chef 16 compatability and modern resource
zuazo/ssh_authorized_keys-cookbook pull request #16
Opened 2020-08-03 20:36 UTC by Stromweld

### Description

Adds resource written from definition making it compatible with chef 16

### Issues Resolved

possibly #14 

### Contribution Check List

- [ ] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README and metadata if applicable.

See [CONTRIBUTING.md](https://github.com/zuazo/ssh_authorized_keys-cookbook/blob/master/CONTRIBUTING.md).

2020-08-06 01:58 UTC, Stromweld commented
@zuazo This PR is to add resource while maintaining backward compatability with older clients

2020-08-08 13:44 UTC, zuazo requested changes
First of all, thanks for the super big update :+1:

I added some comments about version constraints and I would prefer if you remove the changed related to the release bump. Please, if you could review the commented changes.

Thanks again!

2020-08-08 13:44 UTC, zuazo commented on CHANGELOG.md
> +[![Build Status](https://img.shields.io/travis/zuazo/ssh_authorized_keys-cookbook/0.4.0.svg?style=flat)](https://travis-ci.org/zuazo/ssh_authorized_keys-cookbook)
Could you, please, remove this release related changes from the PR? The new version is still not released. Maybe you can put something like "Unreleased" or something like that.

2020-08-08 13:44 UTC, zuazo commented on Gemfile
> +  gem 'kitchen-digitalocean'
Is removing all the version constraints a new recommended pattern in Chef? I'm not against it, but it could break CI tests in the near future.

2020-08-08 13:44 UTC, zuazo commented on CHANGELOG.md
> +
:+1:

2020-08-08 13:44 UTC, zuazo commented on metadata.rb
> +version '1.0.0'
Remove this, please.

2020-08-08 13:44 UTC, zuazo commented on test/integration/default/serverspec/Gemfile
> +gem 'serverspec'
The same question here about removing version constraints.

2020-08-09 12:09 UTC, zuazo commented
Closed by #15. I merged some of your changes by hand. Not the definition/resource name change, though. I hope that's not a big problem for you.

2020-08-09 12:09 UTC, closed without merging

2020-08-09 14:13 UTC, zuazo commented
Relesed in [`1.0.0`](https://github.com/zuazo/ssh_authorized_keys-cookbook/releases/tag/1.0.0)

2020-08-09 16:51 UTC, Stromweld commented
That is not a problem at all, only goal I was looking for is an update that’s compatible with the latest version of chef-infra client 16. Thanks for the update.

On Aug 9, 2020, at 7:09 AM, Xabier de Zuazo <notifications@github.com<mailto:notifications@github.com>> wrote:



Closed by #15<https://github.com/zuazo/ssh_authorized_keys-cookbook/pull/15>. I merged some of your changes by hand. Not the definition/resource name change, though. I hope that's not a big problem for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/zuazo/ssh_authorized_keys-cookbook/pull/16#issuecomment-671044165>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA2QXJ4ARO4H2NHMBMHARTDR72GWRANCNFSM4PTWMK3A>.

2020-08-09 18:53 UTC, zuazo commented
No problem. And thank you for contacting me via email and helping me with the issue! Let me know if there is any problem with the new version.